[[redirects]]
  from = "/cwn/:file"
  to = "/.netlify/images?url=/cwn/:file"
  status = 200

[[redirects]]
  from = "/opg/:file"
  to = "/.netlify/images?url=/opg/:file"
  status = 200

[[redirects]]
  from = "/other/:file"
  to = "/.netlify/images?url=/other/:file"
  status = 200
