[[redirects]]
  from = "cwn/:file"
  to = "/.netlify/images?url=/cwn/:file"
  status = 200
  from = "opg/:file"
  to = "/.netlify/images?url=/opg/:file"
  status = 200
  from = "other/:file"
  to = "/.netlify/images?url=/other/:file"
  status = 200
