[[redirects]]
  # Requests to URLs matching this pattern...
  from = "/images/full/:file"
  # ...will resolve to this URL pattern
  to = "/.netlify/images?url=/images/:file"
  # ... and the status code of 200 will make this behave as a rewrite
  status = 200
